import React, { useContext, useEffect } from 'react';
import { useRouter } from 'next/router';
import { AuthContext } from '../context/auth-context';
import Head from 'next/head';
import HomePage from '../components/HomePage';

export default function Home() {

  return (
    <div>
      <Head>
        <title>Actions</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage />
    </div>
  )
}
